/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicSteamLoginRouteImport } from './routes/api/public/steam/login'
import { Route as ApiPublicSteamCallbackRouteImport } from './routes/api/public/steam/callback'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSteamLoginRoute = ApiPublicSteamLoginRouteImport.update({
  id: '/api/public/steam/login',
  path: '/api/public/steam/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSteamCallbackRoute = ApiPublicSteamCallbackRouteImport.update({
  id: '/api/public/steam/callback',
  path: '/api/public/steam/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/steam/callback': typeof ApiPublicSteamCallbackRoute
  '/api/public/steam/login': typeof ApiPublicSteamLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/steam/callback': typeof ApiPublicSteamCallbackRoute
  '/api/public/steam/login': typeof ApiPublicSteamLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/steam/callback': typeof ApiPublicSteamCallbackRoute
  '/api/public/steam/login': typeof ApiPublicSteamLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketplace'
    | '/profile'
    | '/auth/callback'
    | '/api/public/steam/callback'
    | '/api/public/steam/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marketplace'
    | '/profile'
    | '/auth/callback'
    | '/api/public/steam/callback'
    | '/api/public/steam/login'
  id:
    | '__root__'
    | '/'
    | '/marketplace'
    | '/profile'
    | '/auth/callback'
    | '/api/public/steam/callback'
    | '/api/public/steam/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ProfileRoute: typeof ProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicSteamCallbackRoute: typeof ApiPublicSteamCallbackRoute
  ApiPublicSteamLoginRoute: typeof ApiPublicSteamLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/steam/login': {
      id: '/api/public/steam/login'
      path: '/api/public/steam/login'
      fullPath: '/api/public/steam/login'
      preLoaderRoute: typeof ApiPublicSteamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/steam/callback': {
      id: '/api/public/steam/callback'
      path: '/api/public/steam/callback'
      fullPath: '/api/public/steam/callback'
      preLoaderRoute: typeof ApiPublicSteamCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketplaceRoute: MarketplaceRoute,
  ProfileRoute: ProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicSteamCallbackRoute: ApiPublicSteamCallbackRoute,
  ApiPublicSteamLoginRoute: ApiPublicSteamLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
